cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: pmtiles-cli
project_slug_no_hyphen: pmtiles_cli
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: nofurtherinformation
creator_github_username: nofurtherinformation
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Dylan Halpern
email: halperndc@gmail.com
project_name: pmtiles-cli
project_short_description: A tool to convert geospatial data to PM-tiles
version: 0.1.0
license: BSD
